version: "3.8"

services:
  app:
    build:
      context: ./src
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
      - REDIS_URL=redis://redis:6379
      - WORKER_COUNT=8
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always

volumes:
  db_data:
