# Use the official Node.js image as the base
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json into the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code to the working directory
COPY . .

# Build the application to generate the src/dist folder
RUN npm run build

# Install Nodemon globally

RUN npm install -g nodemon webpack

# Expose the application port (adjust to your correct port)
EXPOSE 3000

# CMD to use Webpack in watch mode and Nodemon to reload
CMD ["npm", "run", "dev:watch", "--prefix", "src"]